/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'screencasts' at '10.02.17 16:02' with Gradle 2.12
 *
 * @author screencasts, @date 10.02.17 16:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
